import type { IBox, IVial, ICellLine } from "./interfaces";

export const fakeBoxData: IBox[] = [
  {
    id: 'box_id_1',
    userId: 'user_id_1',
    name: 'Box 1',
    rows: 9,
    columns: 9,
    essential: true,
    archived: false,
  },
  {
    id: 'box_id_2',
    userId: 'user_id_1',
    name: 'Box 2',
    rows: 9,
    columns: 9,
    essential: false,
    archived: false,
  },
  {
    id: 'box_id_3',
    userId: 'user_id_1',
    name: 'Box 3',
    rows: 9,
    columns: 9,
    essential: false,
    archived: false,
  }
];

export const fakeVialData: IVial[] = [
  {
    id: 'vial_id_1',
    userId: 'user_id_1',
    boxId: 'box_id_1',
    cellLineId: 'cell_line_id_1',
    name: 'Vial 1',
    position: {row: 1, col: 1},
  },
  {
    id: 'vial_id_2',
    userId: 'user_id_1',
    boxId: 'box_id_1',
    cellLineId: 'cell_line_id_2',
    name: 'Vial 2',
    position: {row: 1, col: 2},
  },
  {
    id: 'vial_id_3',
    userId: 'user_id_1',
    boxId: 'box_id_1',
    cellLineId: 'cell_line_id_3',
    name: 'Vial 3',
    position: {row: 2, col: 1},
  },
  {
    id: 'vial_id_4',
    userId: 'user_id_1',
    boxId: 'box_id_2',
    cellLineId: 'cell_line_id_4',
    name: 'Vial 4',
    position: {row: 3, col: 1},
  },
];

export const fakeCellData: ICellLine[] = [
  {
    id: 'cell_line_id_1',
    userId: 'user_id_1',
    name: 'DND41',
    description: 'Human T-cell acute lymphoblastic leukemia',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#38bdf8',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'T-ALL',
    tissueTag: 'T-cell',
  },
  {
    id: 'cell_line_id_2',
    userId: 'user_id_1',
    name: 'Jurkat',
    description: 'Jurkat E6-1 human T-cell leukemia',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#34d399',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'T-cell leukemia',
    tissueTag: 'T-cell',
  },
  {
    id: 'cell_line_id_3',
    userId: 'user_id_1',
    name: 'KOPTK1',
    description: 'Human T-ALL cell line',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#e879f9',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'T-ALL',
    tissueTag: 'T-cell',
  },
  {
    id: 'cell_line_id_4',
    userId: 'user_id_1',
    name: 'CUTLL-1',
    description: 'Human T-ALL (CUTLL-1 / Cuttl1)',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#c084fc',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'T-ALL',
    tissueTag: 'T-cell',
  },
  {
    id: 'cell_line_id_5',
    userId: 'user_id_1',
    name: 'HPBALL',
    description: 'Human T-cell leukemia (DSMZ-certified)',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#fb923c',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'T-ALL',
    tissueTag: 'T-cell',
  },
  {
    id: 'cell_line_id_6',
    userId: 'user_id_1',
    name: 'ALL-SIL',
    description: 'Human T-ALL cell line',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#60a5fa',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'T-ALL',
    tissueTag: 'T-cell',
  },
  {
    id: 'cell_line_id_7',
    userId: 'user_id_1',
    name: 'TALL-1',
    description: 'Human T-cell leukemia/lymphoma',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#86efac',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'T-cell lymphoma',
    tissueTag: 'T-cell',
  },
  {
    id: 'cell_line_id_8',
    userId: 'user_id_1',
    name: 'Granta519',
    description: 'Human mantle cell lymphoma (MCL)',
    category: 'Human B-cell / Mantle Cell Lymphoma',
    color: '#a78bfa',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'MCL',
    tissueTag: 'B-cell/MCL',
  },
  {
    id: 'cell_line_id_9',
    userId: 'user_id_1',
    name: 'Rec1',
    description: 'Human mantle cell lymphoma',
    category: 'Human B-cell / Mantle Cell Lymphoma',
    color: '#f87171',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'MCL',
    tissueTag: 'B-cell/MCL',
  },
  {
    id: 'cell_line_id_10',
    userId: 'user_id_1',
    name: 'SP49',
    description: 'Human MCL cell line',
    category: 'Human B-cell / Mantle Cell Lymphoma',
    color: '#4ade80',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'MCL',
    tissueTag: 'B-cell/MCL',
  },
  {
    id: 'cell_line_id_11',
    userId: 'user_id_1',
    name: 'Mino',
    description: 'Human mantle cell lymphoma',
    category: 'Human B-cell / Mantle Cell Lymphoma',
    color: '#7dd3fc',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'MCL',
    tissueTag: 'B-cell/MCL',
  },
  {
    id: 'cell_line_id_12',
    userId: 'user_id_1',
    name: 'JEKO-1',
    description: 'Human MCL cell line',
    category: 'Human B-cell / Mantle Cell Lymphoma',
    color: '#67e8f9',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'MCL',
    tissueTag: 'B-cell/MCL',
  },
  {
    id: 'cell_line_id_13',
    userId: 'user_id_1',
    name: 'CCMCL1',
    description: 'Millipore CCMCL1 MCL line',
    category: 'Human B-cell / Mantle Cell Lymphoma',
    color: '#67e8f9',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'MCL',
    tissueTag: 'B-cell/MCL',
  },
  {
    id: 'cell_line_id_14',
    userId: 'user_id_1',
    name: 'Primary MCL PBMC',
    description: 'Patient-derived MCL PBMCs',
    category: 'Human B-cell / Mantle Cell Lymphoma',
    color: '#67e8f9',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'MCL',
    tissueTag: 'primary',
  },
  {
    id: 'cell_line_id_15',
    userId: 'user_id_1',
    name: 'RL-MCL-14',
    description: 'Primary MCL sample #8419',
    category: 'Human B-cell / Mantle Cell Lymphoma',
    color: '#67e8f9',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'MCL',
    tissueTag: 'primary',
  },
  {
    id: 'cell_line_id_16',
    userId: 'user_id_1',
    name: 'MEC1',
    description: 'Human chronic lymphocytic leukemia (CLL)',
    category: 'Human B-cell Leukemia / Other',
    color: '#fbbf24',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'CCL',
    tissueTag: 'B-cell/CLL',
  },
  {
    id: 'cell_line_id_17',
    userId: 'user_id_1',
    name: 'PGA1',
    description: 'Human MCL cell line',
    category: 'Human B-cell Leukemia / Other',
    color: '#fbbf24',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'MCL',
    tissueTag: 'B-cell/MCL',
  },
  {
    id: 'cell_line_id_18',
    userId: 'user_id_1',
    name: 'JVM2',
    description: 'Human MCL/B-CLL cell line',
    category: 'Human B-cell Leukemia / Other',
    color: '#fbbf24',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'MCL',
    tissueTag: 'B-cell/MCL',
  },
  {
    id: 'cell_line_id_19',
    userId: 'user_id_1',
    name: 'GM12878',
    description: 'Normal human B-lymphoblastoid (EBV-transformed)',
    category: 'Human B-cell Leukemia / Other',
    color: '#a5f3fc',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'normal',
    tissueTag: 'B-cell',
  },
  {
    id: 'cell_line_id_20',
    userId: 'user_id_1',
    name: 'NALM16',
    description: 'Human B-cell acute lymphoblastic leukemia',
    category: 'Human B-cell Leukemia / Other',
    color: '#60a5fa',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'B-ALL',
    tissueTag: 'B-cell',
  },
  {
    id: 'cell_line_id_21',
    userId: 'user_id_1',
    name: 'REH',
    description: 'Human B-ALL cell line',
    category: 'Human B-cell Leukemia / Other',
    color: '#60a5fa',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'B-ALL',
    tissueTag: 'B-cell',
  },
  {
    id: 'cell_line_id_22',
    userId: 'user_id_1',
    name: 'U266',
    description: 'Human multiple myeloma',
    category: 'Human Multiple Myeloma',
    color: '#fbbf24',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'myeloma',
    tissueTag: 'plasma cell',
  },
  {
    id: 'cell_line_id_23',
    userId: 'user_id_1',
    name: 'RPMI 8226',
    description: 'Human multiple myeloma',
    category: 'Human Multiple Myeloma',
    color: '#fbbf24',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'myeloma',
    tissueTag: 'plasma cell',
  },
  {
    id: 'cell_line_id_24',
    userId: 'user_id_1',
    name: 'KMS11',
    description: 'Human multiple myeloma',
    category: 'Human Multiple Myeloma',
    color: '#fbbf24',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'myeloma',
    tissueTag: 'plasma cell',
  },
  {
    id: 'cell_line_id_25',
    userId: 'user_id_1',
    name: 'MMIS',
    description: 'Human multiple myeloma',
    category: 'Human Multiple Myeloma',
    color: '#fbbf24',
    speciesTag: 'human',
    growthTag: 'suspension',
    diseaseTag: 'myeloma',
    tissueTag: 'plasma cell',
  },
  {
    id: 'cell_line_id_26',
    userId: 'user_id_1',
    name: 'MB157',
    description: 'MDA-MB-157 triple-negative breast cancer',
    category: 'Human breast cancer',
    color: '#f472b6',
    speciesTag: 'human',
    growthTag: 'adherent',
    diseaseTag: 'breast cancer',
    tissueTag: 'breast (TNBC)',
  },
  {
    id: 'cell_line_id_27',
    userId: 'user_id_1',
    name: 'MCF7',
    description: 'Human breast cancer, ER+',
    category: 'Human breast cancer',
    color: '#fda4af',
    speciesTag: 'human',
    growthTag: 'adherent',
    diseaseTag: 'breast cancer',
    tissueTag: 'breast (ER+)',
  },
  {
    id: 'cell_line_id_28',
    userId: 'user_id_1',
    name: 'HCC1599',
    description: 'Human TNBC cell line',
    category: 'Human breast cancer',
    color: '#facc15',
    speciesTag: 'human',
    growthTag: 'adherent',
    diseaseTag: 'breast cancer',
    tissueTag: 'breast (TNBC)',
  },
  {
    id: 'cell_line_id_29',
    userId: 'user_id_1',
    name: 'MDA-MB-231',
    description: 'Human TNBC, highly metastatic',
    category: 'Human breast cancer',
    color: '#d9f99d',
    speciesTag: 'human',
    growthTag: 'adherent',
    diseaseTag: 'breast cancer',
    tissueTag: 'breast (TNBC)',
  },
  {
    id: 'cell_line_id_30',
    userId: 'user_id_1',
    name: 'MDA-MB-468',
    description: 'Human TNBC cell line',
    category: 'Human breast cancer',
    color: '#d9f99d',
    speciesTag: 'human',
    growthTag: 'adherent',
    diseaseTag: 'breast cancer',
    tissueTag: 'breast (TNBC)',
  },
  {
    id: 'cell_line_id_31',
    userId: 'user_id_1',
    name: 'SUM149',
    description: 'SUM149PT inflammatory breast cancer',
    category: 'Human breast cancer',
    color: '#f9a8d4',
    speciesTag: 'human',
    growthTag: 'adherent',
    diseaseTag: 'breast cancer',
    tissueTag: 'breast (TNBC)',
  },
  {
    id: 'cell_line_id_32',
    userId: 'user_id_1',
    name: '293T',
    description: 'HEK293T lentiviral packaging cell line',
    category: 'Packaging / Tool lines',
    color: '#fdba74',
    speciesTag: 'human',
    growthTag: 'adherent',
    diseaseTag: 'normal/transformed',
    tissueTag: 'HEK',
  },
  {
    id: 'cell_line_id_33',
    userId: 'user_id_1',
    name: 'PlatE',
    description: 'Mouse retroviral packaging line (Plat-E)',
    category: 'Packaging / Tool lines',
    color: '#6ee7b7',
    speciesTag: 'mouse',
    growthTag: 'adherent',
    diseaseTag: 'normal/transformed',
    tissueTag: 'retroviral packaging',
  },
  {
    id: 'cell_line_id_34',
    userId: 'user_id_1',
    name: 'RAG 1-1',
    description: 'Mouse B-cell line',
    category: 'Mouse B-cell lines',
    color: '#6ee7b7',
    speciesTag: 'mouse',
    growthTag: 'suspension',
    diseaseTag: 'B-cell',
    tissueTag: 'mouse B-cell',
  },
  {
    id: 'cell_line_id_35',
    userId: 'user_id_1',
    name: '38B9',
    description: 'Mouse pre-B ALL cell line',
    category: 'Mouse B-cell lines',
    color: '#6ee7b7',
    speciesTag: 'mouse',
    growthTag: 'suspension',
    diseaseTag: 'pre-B-cell',
    tissueTag: 'mouse B-cell',
  },
  {
    id: 'cell_line_id_36',
    userId: 'user_id_1',
    name: '445*3',
    description: 'Mouse B-ALL line',
    category: 'Mouse B-cell lines',
    color: '#6ee7b7',
    speciesTag: 'mouse',
    growthTag: 'suspension',
    diseaseTag: 'B-ALL',
    tissueTag: 'mouse B-cell',
  },
  {
    id: 'cell_line_id_37',
    userId: 'user_id_1',
    name: '3-1',
    description: 'Mouse B-ALL line',
    category: 'Mouse B-cell lines',
    color: '#6ee7b7',
    speciesTag: 'mouse',
    growthTag: 'suspension',
    diseaseTag: 'B-ALL',
    tissueTag: 'mouse B-cell',
  },
  {
    id: 'cell_line_id_38',
    userId: 'user_id_1',
    name: '5194',
    description: 'Mouse B-cell lymphoma line',
    category: 'Mouse B-cell lines',
    color: '#6ee7b7',
    speciesTag: 'mouse',
    growthTag: 'suspension',
    diseaseTag: 'B-ALL',
    tissueTag: 'mouse B-cell',
  },
  {
    id: 'cell_line_id_39',
    userId: 'user_id_1',
    name: 'A70',
    description: 'Mouse B-cell line',
    category: 'Mouse B-cell lines',
    color: '#6ee7b7',
    speciesTag: 'mouse',
    growthTag: 'suspension',
    diseaseTag: 'B-cell',
    tissueTag: 'mouse B-cell',
  },
];

export const speciesTagColorMap: Record<string, string> = {
  "human": "#7dd3fc",
  "mouse": "#86efac",
};

export const growthTagColorMap: Record<string, string> = {
  "suspension": "#c4b5fd",
  "adherent": "#fdba74",
};

export const diseaseTagColor: string = "#fca5a5";
export const tissueTagColor: string = "#f9a8d4";

