import type { IBox, IVial, ICellLine } from "./interfaces";

export const fakeBoxData: IBox[] = [
  {
    id: 'box_id_1',
    userId: 'user_id_1',
    name: 'Box 1',
    rows: 9,
    columns: 9,
    essential: true,
    archived: false,
  },
  {
    id: 'box_id_2',
    userId: 'user_id_1',
    name: 'Box 2',
    rows: 9,
    columns: 9,
    essential: false,
    archived: false,
  },
  {
    id: 'box_id_3',
    userId: 'user_id_1',
    name: 'Box 3',
    rows: 9,
    columns: 9,
    essential: false,
    archived: false,
  }
];

export const fakeVialData: IVial[] = [
  {
    id: 'vial_id_1',
    userId: 'user_id_1',
    boxId: 'box_id_1',
    cellLineId: 'ojxhiu2n8y2jyubv3tf8t2639x7yh89j',
    name: 'Vial 1',
    position: {row: 1, col: 1},
  },
  {
    id: 'vial_id_2',
    userId: 'user_id_1',
    boxId: 'box_id_1',
    cellLineId: 'm9hxy3782hx98ju2bg8h2jy238nbxy2b36t7x',
    name: 'Vial 2',
    position: {row: 1, col: 2},
  },
  {
    id: 'vial_id_3',
    userId: 'user_id_1',
    boxId: 'box_id_1',
    cellLineId: 'd3fgnc3jiuhc8gh8349jcf34c3fhc8',
    name: 'Vial 3',
    position: {row: 2, col: 1},
  },
  {
    id: 'vial_id_4',
    userId: 'user_id_1',
    boxId: 'box_id_2',
    cellLineId: '2d2d32evrwft4g4gt4dx23c',
    name: 'Vial 4',
    position: {row: 3, col: 1},
  },
];

export const cellData: ICellLine[] = [
  {
    id: 'ojxhiu2n8y2jyubv3tf8t2639x7yh89j',
    userId: 'user_id_1',
    name: 'DND41',
    description: 'Human T-cell acute lymphoblastic leukemia',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#38bdf8',
    tags: ['human', 'suspension', 'T-ALL', 'T-cell'],
  },
  {
    id: 'm9hxy3782hx98ju2bg8h2jy238nbxy2b36t7x',
    userId: 'user_id_1',
    name: 'Jurkat',
    description: 'Jurkat E6-1 human T-cell leukemia',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#34d399',
    tags: ['human', 'suspension', 'T-cell leukemia', 'T-cell'],
  },
  {
    id: 'd3fgnc3jiuhc8gh8349jcf34c3fhc8',
    userId: 'user_id_1',
    name: 'KOPTK1',
    description: 'Human T-ALL cell line',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#e879f9',
    tags: ['human', 'suspension', 'T-ALL', 'T-cell'],
  },
  {
    id: 'df45vbnm98nhg6f54d32d4fgb',
    userId: 'user_id_1',
    name: 'CUTLL-1',
    description: 'Human T-ALL (CUTLL-1 / Cuttl1)',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#c084fc',
    tags: ['human', 'suspension', 'T-ALL', 'T-cell'],
  },
  {
    id: 'vbnm8yjhgfdvbnh4eg5v',
    userId: 'user_id_1',
    name: 'HPBALL',
    description: 'Human T-cell leukemia (DSMZ-certified)',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#fb923c',
    tags: ['human', 'suspension', 'T-ALL', 'T-cell'],
  },
  {
    id: 'c6v56by5bd323erfdgvf',
    userId: 'user_id_1',
    name: 'ALL-SIL',
    description: 'Human T-ALL cell line',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#60a5fa',
    tags: ['human', 'suspension', 'T-ALL', 'T-cell'],
  },
  {
    id: 'okcjhb8jfj28jdm9230',
    userId: 'user_id_1',
    name: 'TALL-1',
    description: 'Human T-cell leukemia/lymphoma',
    category: 'Human T-cell Leukemia / Lymphoma',
    color: '#86efac',
    tags: ['human', 'suspension', 'T-cell lymphoma', 'T-cell'],
  },
  {
    id: '2d2d32evrwft4g4gt4dx23c',
    userId: 'user_id_1',
    name: 'Granta519',
    description: 'Human mantle cell lymphoma (MCL)',
    category: 'Human B-cell / Mantle Cell Lymphoma',
    color: '#91d62f',
    tags: ['human', 'suspension', 'MCL', 'B-cell/MCL'],
  },
];

export const tagColorMap: Record<string, string> = {
  "human": "#7dd3fc",
  "suspension": "#c4b5fd",
  "T-cell": "#f9a8d4",
  "T-ALL": "#fca5a5",
  "T-cell leukemia": "#fca5a5",
  "T-cell lymphoma": "#fca5a5",
};